-- FontMarket Database Initialization Script
-- This script creates the necessary collections and indexes for MongoDB

-- Users Collection Indexes
db.users.createIndex({ "email": 1 }, { unique: true })
db.users.createIndex({ "username": 1 }, { unique: true })
db.users.createIndex({ "role": 1 })
db.users.createIndex({ "createdAt": -1 })

-- Fonts Collection Indexes  
db.fonts.createIndex({ "sellerId": 1 })
db.fonts.createIndex({ "category": 1 })
db.fonts.createIndex({ "status": 1 })
db.fonts.createIndex({ "featured": 1 })
db.fonts.createIndex({ "isFree": 1 })
db.fonts.createIndex({ "name": "text", "description": "text", "tags": "text" })
db.fonts.createIndex({ "createdAt": -1 })
db.fonts.createIndex({ "downloads": -1 })
db.fonts.createIndex({ "rating": -1 })

-- Chat Messages Collection Indexes
db.chatMessages.createIndex({ "conversationId": 1, "createdAt": -1 })
db.chatMessages.createIndex({ "senderId": 1 })
db.chatMessages.createIndex({ "receiverId": 1 })
db.chatMessages.createIndex({ "readAt": 1 })

-- Orders Collection Indexes
db.orders.createIndex({ "buyerId": 1 })
db.orders.createIndex({ "sellerId": 1 })
db.orders.createIndex({ "fontId": 1 })
db.orders.createIndex({ "paymentStatus": 1 })
db.orders.createIndex({ "createdAt": -1 })

-- Reviews Collection Indexes
db.reviews.createIndex({ "fontId": 1 })
db.reviews.createIndex({ "buyerId": 1 })
db.reviews.createIndex({ "sellerId": 1 })
db.reviews.createIndex({ "createdAt": -1 })

-- Notifications Collection Indexes
db.notifications.createIndex({ "userId": 1, "createdAt": -1 })
db.notifications.createIndex({ "read": 1 })
db.notifications.createIndex({ "type": 1 })

-- Insert sample data for testing
db.users.insertOne({
  email: "admin@fontmarket.com",
  password: "$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj/RK.s5uIoO", // password: admin123
  username: "admin",
  displayName: "FontMarket Admin",
  role: "admin",
  language: "en",
  wishlist: [],
  purchasedFonts: [],
  notifications: {
    wishlistPriceChanges: true,
    newFontsFromFollowed: true
  },
  createdAt: new Date(),
  updatedAt: new Date()
})

-- Insert sample font categories
db.fonts.insertMany([
  {
    name: "Modern Sans Pro",
    description: "A clean and modern sans-serif font perfect for digital interfaces and branding.",
    category: "sans-serif",
    tags: ["modern", "clean", "digital", "interface"],
    sellerId: ObjectId(),
    sellerName: "DesignStudio",
    price: 29,
    originalPrice: 39,
    isFree: false,
    fontFiles: [
      {
        format: "otf",
        fileUrl: "/fonts/modern-sans-pro.otf",
        fileSize: 245760
      }
    ],
    previewImages: ["/previews/modern-sans-pro-1.jpg"],
    supportedLanguages: ["latin", "thai"],
    downloads: 1247,
    rating: 4.8,
    reviews: [],
    license: {
      type: "commercial",
      terms: "Standard commercial license included",
      autoGenerated: true
    },
    status: "approved",
    featured: true,
    sponsored: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Elegant Serif",
    description: "A sophisticated serif font with classical proportions, ideal for editorial design.",
    category: "serif",
    tags: ["elegant", "classical", "editorial", "sophisticated"],
    sellerId: ObjectId(),
    sellerName: "TypeFoundry",
    price: 0,
    isFree: true,
    fontFiles: [
      {
        format: "ttf",
        fileUrl: "/fonts/elegant-serif.ttf",
        fileSize: 189440
      }
    ],
    previewImages: ["/previews/elegant-serif-1.jpg"],
    supportedLanguages: ["latin"],
    downloads: 3421,
    rating: 4.6,
    reviews: [],
    license: {
      type: "personal",
      terms: "Free for personal use only",
      autoGenerated: true
    },
    status: "approved",
    featured: false,
    sponsored: false,
    createdAt: new Date(),
    updatedAt: new Date()
  }
])
